### ISSUE TITLE
KeyError: "The name 'import/input' refers to an Operation not in the graph." while using a retrained inception model with tf version 1.11

### ISSUE THREAD

**Issue by o3cloudng** [ActiveState/tensorflask#2]
I have used this tensorflask as it is with the trained model and it works just fine with a little tweak, so i will say you have done a great job. However, I am new to tensorflow and on trying to use my retrained model (.pb) and label (.txt) I am having this errors while trying to run the app.py file

KeyError: "The name 'import/input' refers to an Operation not in the graph."

From some suggected solutions on stackoverflow
`input_layer = "input"`
change to
`input_layer = "Mul"`
which also resulted in the error below:
`KeyError: "The name 'final_result:0' refers to a Tensor which does not exist. The operation, 'final_result', does not exist in the graph."`

Kindly assist.

Thanks for the great work.
[app.txt](https://github.com/ActiveState/tensorflask/files/2616660/app.txt)

**Comment by Yogita98** [comment]
Try to change 
output_layer="final_result"
to
output_layer="output"


It worked for me.
