### ISSUE TITLE
 Attempt to convert a value (<FileStorage: '18-01-10-dog-id-python-tensorflow-flask-02-770px.jpg' ('image/jpeg')>) with an unsupported type (<class 'werkzeug.datastructures.FileStorage'>) to a Tensor.

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [ActiveState/tensorflask#4]
I'm getting the following error how I can fix it?

```ValueError: Attempt to convert a value (<FileStorage: '18-01-10-dog-id-python-tensorflow-flask-02-770px.jpg' ('image/jpeg')>) with an unsupported type (<class 'werkzeug.datastructures.FileStorage'>) to a Tensor.```

Thanks.

**Comment by UnnikrishnanBhargavakurup** [comment]
I was trying to upload file using postman, now it's working fine

**Comment by AnPhamThien** [comment]
how can you fix it ?
